In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [17]:
# Load dataset
df = pd.read_csv("../data/raw/Counselling_system_Dataset.csv")

# Preview
df.head()

,Year,Round,Institute,Branch,Category,Domicile,OpeningRank,ClosingRank,BranchSeats,TotalSeats,TotalCandidates
0,2014.0,R1,MITS,BT,UR/X/OP,Y,78121.0,80003.0,2.0,30.0,1356000.0
1,2014.0,R1,MITS,BT,OBC/X/OP,Y,122826.0,133005.0,3.0,30.0,1356000.0
2,2014.0,R1,MITS,BT,UR/X/OP,Y,99915.0,137259.0,8.0,30.0,1356000.0
3,2014.0,R1,MITS,BT,UR/X/F,Y,113348.0,179038.0,4.0,30.0,1356000.0
4,2014.0,R1,MITS,BT,UR/NCC/OP,Y,190302.0,190302.0,1.0,30.0,1356000.0

In [18]:
df.shape

(6070, 11)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6070 entries, 0 to 6069
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             5936 non-null   float64
 1   Round            5819 non-null   object
 2   Institute        5819 non-null   object
 3   Branch           5819 non-null   object
 4   Category         5819 non-null   object
 5   Domicile         5819 non-null   object
 6   OpeningRank      5819 non-null   float64
 7   ClosingRank      5819 non-null   float64
 8   BranchSeats      5819 non-null   float64
 9   TotalSeats       5818 non-null   float64
 10  TotalCandidates  6062 non-null   float64
dtypes: float64(6), object(5)
memory usage: 521.8+ KB

In [20]:
df.describe()

,Year,OpeningRank,ClosingRank,BranchSeats,TotalSeats,TotalCandidates
count,5936.000000,5.819000e+03,5.819000e+03,5819.000000,5818.000000,6.062000e+03
mean,2020.472877,2.650565e+05,3.735138e+05,6.455920,72.468890,1.173543e+06
std,3.474243,2.411634e+05,3.202344e+05,8.682587,40.332508,1.944839e+05
min,2014.000000,2.000000e+00,9.000000e+00,1.000000,1.000000,9.055900e+05
25%,2017.000000,9.566200e+04,1.283930e+05,1.000000,41.000000,1.020000e+06
50%,2021.000000,1.725180e+05,2.380570e+05,3.000000,63.000000,1.147125e+06
75%,2024.000000,3.612410e+05,5.675400e+05,7.000000,104.000000,1.356000e+06
max,2025.000000,1.466573e+06,1.469201e+06,97.000000,157.000000,1.475103e+06

In [21]:
df.columns = df.columns.str.strip().str.replace(" ", "")

print("Columns:", df.columns.tolist())

Columns: ['Year', 'Round', 'Institute', 'Branch', 'Category', 'Domicile', 'OpeningRank', 'ClosingRank', 'BranchSeats', 'TotalSeats', 'TotalCandidates']

In [22]:
missing = df.isnull().sum()
print("\nMissing Values:\n", missing)

Missing Values:
 Year               134
Round              251
Institute          251
Branch             251
Category           251
Domicile           251
OpeningRank        251
ClosingRank        251
BranchSeats        251
TotalSeats         252
TotalCandidates      8
dtype: int64

In [23]:
num_cols = ["OpeningRank", "ClosingRank", "BranchSeats", "TotalSeats", "TotalCandidates"]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [24]:
# Drop only critical rows
df = df.dropna(subset=["OpeningRank", "ClosingRank"])

# Fill remaining
df["BranchSeats"].fillna(df["BranchSeats"].median(), inplace=True)
df["TotalSeats"].fillna(df["TotalSeats"].median(), inplace=True)

# Very important
df["TotalCandidates"].fillna(method="ffill", inplace=True)

C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\4216450498.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BranchSeats"].fillna(df["BranchSeats"].median(), inplace=True)
C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\4216450498.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TotalSeats"].fillna(df["TotalSeats"].median(), inplace=True)
C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\4216450498.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TotalCandidates"].fillna(method="ffill", inplace=True)
C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\4216450498.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["TotalCandidates"].fillna(method="ffill", inplace=True)

In [25]:
duplicates = df.duplicated()

print("Duplicate rows:", duplicates.sum())

Duplicate rows: 2

In [26]:
df = df.drop_duplicates()

In [27]:
print("Final Shape:", df.shape)
print("\nRemaining Missing:\n", df.isnull().sum())

Final Shape: (5817, 11)

Remaining Missing:
 Year               0
Round              0
Institute          0
Branch             0
Category           0
Domicile           0
OpeningRank        0
ClosingRank        0
BranchSeats        0
TotalSeats         0
TotalCandidates    0
dtype: int64

In [28]:
df

,Year,Round,Institute,Branch,Category,Domicile,OpeningRank,ClosingRank,BranchSeats,TotalSeats,TotalCandidates
0,2014.0,R1,MITS,BT,UR/X/OP,Y,78121.0,80003.0,2.0,30.0,1356000.0
1,2014.0,R1,MITS,BT,OBC/X/OP,Y,122826.0,133005.0,3.0,30.0,1356000.0
2,2014.0,R1,MITS,BT,UR/X/OP,Y,99915.0,137259.0,8.0,30.0,1356000.0
3,2014.0,R1,MITS,BT,UR/X/F,Y,113348.0,179038.0,4.0,30.0,1356000.0
4,2014.0,R1,MITS,BT,UR/NCC/OP,Y,190302.0,190302.0,1.0,30.0,1356000.0
...,...,...,...,...,...,...,...,...,...,...,...
6065,2025.0,INTERNAL,MITS,MECH,UR/X/F,Y,775426.0,775426.0,1.0,8.0,1475103.0
6066,2025.0,INTERNAL,MITS,MECH,UR/X/F,Y,1016946.0,1016946.0,1.0,8.0,1475103.0
6067,2025.0,INTERNAL,MITS,MECH,UR/X/OP,Y,484102.0,484102.0,1.0,8.0,1475103.0
6068,2025.0,INTERNAL,MITS,MECH,UR/X/OP,Y,488769.0,681736.0,3.0,8.0,1475103.0
6069,2025.0,INTERNAL,MITS,MECH,UR/X/OP,Y,178.0,178.0,1.0,8.0,1475103.0

In [29]:
df["ClosingPercentile"] = 1 - (df["ClosingRank"] / df["TotalCandidates"])
df["ClosingPercentile"] = df["ClosingPercentile"].clip(0, 1)

df["OpeningPercentile"] = 1 - (df["OpeningRank"] / df["TotalCandidates"])
df["OpeningPercentile"] = df["OpeningPercentile"].clip(0, 1)

In [30]:
df["BranchShare"] = df["BranchSeats"] / df["TotalSeats"]

In [31]:
df["RankRange"] = df["ClosingRank"] - df["OpeningRank"]
df["MidRank"] = (df["OpeningRank"] + df["ClosingRank"]) / 2

In [32]:
min_year = df["Year"].min()

df["YearWeight"] = 1 + 0.05 * (df["Year"] - min_year)

In [33]:
group_cols = ["Branch", "Category", "Round", "Domicile"]

grouped = df.groupby(group_cols)

In [34]:
stats = grouped.agg({

    "ClosingPercentile": [
        "min",
        "max",
        "mean",
        "std"
    ],

    "TotalSeats": "mean",

    "BranchSeats": "mean",

    "TotalCandidates": "mean"
    
}).reset_index()

stats.columns = [

    "Branch",
    "Category",
    "Round",
    "Domicile",

    "MinP",
    "MaxP",
    "MeanP",
    "StdP",

    "TotalSeats",
    "BranchSeats",
    "TotalCandidates"
]
# FIX IMPORTANT
stats["StdP"] = stats["StdP"].fillna(0)

stats.head(50)

,Branch,Category,Round,Domicile,MinP,MaxP,MeanP,StdP,TotalSeats,BranchSeats,TotalCandidates
0,AI,EWS,INTERNAL,Y,0.854393,0.896604,0.871917,0.017749,82.250000,3.500000,1.460105e+06
1,AI,EWS,R1,Y,0.896558,0.902835,0.899697,0.004438,115.500000,11.000000,1.445106e+06
2,AI,EWS,R1_Upgrade,Y,0.866510,0.884543,0.875526,0.012751,94.000000,9.000000,1.445106e+06
3,AI,EWS,R2,Y,0.885249,0.885249,0.885249,0.000000,25.000000,1.000000,1.415110e+06
4,AI,EWS/S/M,R2,Y,0.899804,0.899804,0.899804,0.000000,58.000000,1.000000,1.475103e+06
5,AI,EWS/X/F,R2,Y,0.899778,0.899778,0.899778,0.000000,58.000000,1.000000,1.475103e+06
6,AI,EWS/X/M,R2,Y,0.898820,0.898820,0.898820,0.000000,58.000000,3.000000,1.475103e+06
7,AI,FW/OP,R1,Y,0.905093,0.905093,0.905093,0.000000,156.000000,6.000000,1.475103e+06
8,AI,FW/OP,R1_Upgrade,Y,0.899284,0.899284,0.899284,0.000000,126.000000,4.000000,1.475103e+06
9,AI,FW/OP,R2,Y,0.905131,0.905131,0.905131,0.000000,58.000000,3.000000,1.475103e+06
10,AI,JKR,R2,N,0.754751,0.754751,0.754751,0.000000,58.000000,1.000000,1.475103e+06
11,AI,OBC/S/F,R1,Y,0.459740,0.459740,0.459740,0.000000,75.000000,1.000000,1.415110e+06
12,AI,OBC/S/OP,INTERNAL,Y,0.403931,0.403931,0.403931,0.000000,98.000000,1.000000,1.475103e+06
13,AI,OBC/S/OP,R1,Y,0.834216,0.834216,0.834216,0.000000,156.000000,1.000000,1.475103e+06
14,AI,OBC/S/OP,R1_Upgrade,Y,0.724706,0.724706,0.724706,0.000000,126.000000,1.000000,1.475103e+06
15,AI,OBC/X/F,INTERNAL,Y,0.701243,0.701243,0.701243,0.000000,98.000000,3.000000,1.475103e+06
16,AI,OBC/X/F,R1,Y,0.844162,0.860383,0.852273,0.011470,115.500000,3.500000,1.445106e+06
17,AI,OBC/X/F,R1_Upgrade,Y,0.784444,0.843953,0.814198,0.042079,94.000000,3.000000,1.445106e+06
18,AI,OBC/X/OP,INTERNAL,Y,0.676536,0.818254,0.749553,0.062451,72.800000,8.200000,1.451106e+06
19,AI,OBC/X/OP,R1,Y,0.863111,0.892761,0.877936,0.020966,115.500000,10.500000,1.445106e+06
20,AI,OBC/X/OP,R1_Upgrade,Y,0.763132,0.812444,0.787788,0.034868,94.000000,29.000000,1.445106e+06
21,AI,SC/S/F,R2,Y,0.537568,0.537568,0.537568,0.000000,58.000000,1.000000,1.475103e+06
22,AI,SC/X/F,R1,Y,0.143482,0.629574,0.386528,0.343720,115.500000,4.500000,1.445106e+06
23,AI,SC/X/F,R1_Upgrade,Y,0.374336,0.685225,0.529780,0.219831,94.000000,1.000000,1.445106e+06
24,AI,SC/X/OP,INTERNAL,Y,0.238570,0.659599,0.396848,0.182517,66.500000,1.250000,1.445106e+06
25,AI,SC/X/OP,R1,Y,0.087188,0.362522,0.224855,0.194690,115.500000,32.000000,1.445106e+06
26,AI,SC/X/OP,R1_Upgrade,Y,0.145647,0.159689,0.152668,0.009930,94.000000,6.000000,1.445106e+06
27,AI,SC/X/OP,R2,Y,0.204120,0.265223,0.235971,0.030634,47.000000,10.666667,1.455105e+06
28,AI,ST/X/F,R1,Y,0.046242,0.353023,0.199632,0.216927,115.500000,1.500000,1.445106e+06
29,AI,ST/X/OP,R1,Y,0.014825,0.204710,0.109767,0.134269,115.500000,1.000000,1.445106e+06
30,AI,ST/X/OP,R1_Upgrade,Y,0.014825,0.014825,0.014825,0.000000,62.000000,1.000000,1.415110e+06
31,AI,ST/X/OP,R2,Y,0.011357,0.011357,0.011357,0.000000,58.000000,1.000000,1.475103e+06
32,AI,UR/S/OP,INTERNAL,Y,0.734187,0.856145,0.778406,0.067536,77.000000,1.000000,1.455105e+06
33,AI,UR/S/OP,R1,Y,0.714686,0.744886,0.729786,0.021354,115.500000,2.000000,1.445106e+06
34,AI,UR/S/OP,R1_Upgrade,Y,0.591741,0.744886,0.668314,0.108290,94.000000,1.500000,1.445106e+06
35,AI,UR/X/F,INTERNAL,Y,0.788374,0.875362,0.838296,0.032926,77.000000,2.666667,1.455105e+06
36,AI,UR/X/F,R1,Y,0.872072,0.893844,0.882958,0.015395,115.500000,10.500000,1.445106e+06
37,AI,UR/X/F,R1_Upgrade,Y,0.842285,0.866856,0.854570,0.017374,94.000000,9.500000,1.445106e+06
38,AI,UR/X/F,R2,Y,0.852735,0.871837,0.864343,0.010194,47.000000,3.000000,1.455105e+06
39,AI,UR/X/OP,INTERNAL,AI,0.792758,0.850025,0.813216,0.031943,77.000000,3.000000,1.455105e+06
40,AI,UR/X/OP,INTERNAL,Y,0.809442,0.863488,0.831239,0.021453,80.000000,5.857143,1.457962e+06
41,AI,UR/X/OP,R1,AI,0.936858,0.940550,0.938704,0.002611,115.500000,4.500000,1.445106e+06
42,AI,UR/X/OP,R1,Y,0.882133,0.898544,0.890339,0.011605,115.500000,30.500000,1.445106e+06
43,AI,UR/X/OP,R1_Upgrade,AI,0.908674,0.921508,0.915091,0.009075,94.000000,4.500000,1.445106e+06
44,AI,UR/X/OP,R1_Upgrade,Y,0.835514,0.863488,0.849501,0.019781,94.000000,27.500000,1.445106e+06
45,AI,UR/X/OP,R2,AI,0.894629,0.939037,0.919587,0.022710,47.000000,1.666667,1.455105e+06
46,AI,UR/X/OP,R2,Y,0.876496,0.881984,0.880099,0.002451,49.750000,6.250000,1.460105e+06
47,AIAIDS,EWS,INTERNAL,Y,0.825513,0.913342,0.882119,0.028589,42.166667,1.750000,1.220540e+06
48,AIAIDS,EWS,R1,Y,0.867173,0.909607,0.893123,0.018247,75.600000,6.800000,1.169627e+06
49,AIAIDS,EWS,R1_Upgrade,Y,0.836726,0.899573,0.873352,0.024366,61.800000,4.000000,1.169627e+06

In [35]:
import numpy as np

# 🔥 Using ClosingPercentile instead of MidPercentile

def calculate_trend(group):

    group = group.sort_values("Year")

    x = group["Year"].values
    y = group["ClosingPercentile"].values   # ✅ CHANGED HERE

    # Remove invalid values
    mask = np.isfinite(x) & np.isfinite(y)

    x = x[mask]
    y = y[mask]

    # Safety checks
    if len(x) < 2:
        return 0.0

    if np.std(x) == 0 or np.std(y) == 0:
        return 0.0

    # Center years for numerical stability
    x = x - x.mean()

    try:
        slope = np.polyfit(x, y, 1)[0]

        # Optional clipping (recommended)
        slope = np.clip(slope, -0.1, 0.1)

        return float(slope)

    except:
        return 0.0

In [36]:
group_cols = ["Branch", "Category", "Round", "Domicile"]  # + "Domicile" if you include it

trend_df = (
    df.groupby(group_cols)
      .apply(calculate_trend, include_groups=False)
      .reset_index(name="Trend")
)

In [37]:
trend_df["Trend"] = trend_df["Trend"].clip(-0.1, 0.1)

In [38]:
final_df = stats.merge(trend_df, on=group_cols)

final_df.to_csv("../data/processed/final_df.csv", index=False)

print("✅ Feature engineering complete")

✅ Feature engineering complete

In [39]:
import pandas as pd
import numpy as np

# Raw dataset
raw_df = pd.read_csv("../data/raw/Counselling_system_Dataset.csv")
raw_df.head()

,Year,Round,Institute,Branch,Category,Domicile,OpeningRank,ClosingRank,BranchSeats,TotalSeats,TotalCandidates
0,2014.0,R1,MITS,BT,UR/X/OP,Y,78121.0,80003.0,2.0,30.0,1356000.0
1,2014.0,R1,MITS,BT,OBC/X/OP,Y,122826.0,133005.0,3.0,30.0,1356000.0
2,2014.0,R1,MITS,BT,UR/X/OP,Y,99915.0,137259.0,8.0,30.0,1356000.0
3,2014.0,R1,MITS,BT,UR/X/F,Y,113348.0,179038.0,4.0,30.0,1356000.0
4,2014.0,R1,MITS,BT,UR/NCC/OP,Y,190302.0,190302.0,1.0,30.0,1356000.0

In [40]:
# Feature dataset
final_df = pd.read_csv("../data/processed/final_df.csv")
final_df.head()

,Branch,Category,Round,Domicile,MinP,MaxP,MeanP,StdP,TotalSeats,BranchSeats,TotalCandidates,Trend
0,AI,EWS,INTERNAL,Y,0.854393,0.896604,0.871917,0.017749,82.25,3.5,1460104.75,0.003166
1,AI,EWS,R1,Y,0.896558,0.902835,0.899697,0.004438,115.50,11.0,1445106.50,-0.006277
2,AI,EWS,R1_Upgrade,Y,0.866510,0.884543,0.875526,0.012751,94.00,9.0,1445106.50,-0.018033
3,AI,EWS,R2,Y,0.885249,0.885249,0.885249,0.000000,25.00,1.0,1415110.00,0.000000
4,AI,EWS/S/M,R2,Y,0.899804,0.899804,0.899804,0.000000,58.00,1.0,1475103.00,0.000000

In [41]:
# Show all available years in the dataset
available_years = sorted(raw_df["Year"].unique())

print("Available Years:", available_years)

# Choose any year manually
selected_year = int(input("Enter the year you want to select: "))

# Check if the year exists in dataset
if selected_year in available_years:
    print("Selected Year:", selected_year)

else:
    print("Year not found in dataset.")

Available Years: [np.float64(2014.0), np.float64(nan), np.float64(2015.0), np.float64(2016.0), np.float64(2017.0), np.float64(2018.0), np.float64(2019.0), np.float64(2020.0), np.float64(2021.0), np.float64(2022.0), np.float64(2023.0), np.float64(2024.0), np.float64(2025.0)]
Selected Year: 2024

In [42]:
CURRENT_TOTAL_CANDIDATES = (
    raw_df[raw_df["Year"] == selected_year]["TotalCandidates"]
    .iloc[0]
)

print("Current Total Candidates:", CURRENT_TOTAL_CANDIDATES)

Current Total Candidates: 1415110.0

In [43]:
user_rank = 91040
user_category = "UR/X/OP"
user_round = "R1"
user_domicile = "Y"

In [44]:
CURRENT_TOTAL_CANDIDATES = int(CURRENT_TOTAL_CANDIDATES)

user_percentile = 1 - (user_rank / CURRENT_TOTAL_CANDIDATES)

print("User Percentile:", user_percentile)

User Percentile: 0.9356657786320498

In [45]:
filtered_df = final_df[
    (final_df["Category"] == user_category) &
    (final_df["Round"] == user_round) &
    (final_df["Domicile"] == user_domicile)
]

filtered_df.head()

,Branch,Category,Round,Domicile,MinP,MaxP,MeanP,StdP,TotalSeats,BranchSeats,TotalCandidates,Trend
42,AI,UR/X/OP,R1,Y,0.882133,0.898544,0.890339,0.011605,115.5,30.500,1445106.500,-0.016411
91,AIAIDS,UR/X/OP,R1,Y,0.823665,0.912559,0.881559,0.035552,75.6,19.600,1169627.200,0.019270
136,AIML,UR/X/OP,R1,Y,0.801801,0.908346,0.874157,0.045577,74.2,20.400,1169627.200,0.026342
167,AIR,UR/X/OP,R1,Y,0.895425,0.895425,0.895425,0.000000,69.0,20.000,1023000.000,0.000000
208,AUTO,UR/X/OP,R1,Y,0.004568,0.881417,0.635342,0.364870,59.5,19.125,1070715.375,-0.100000

In [46]:
filtered_df["ExpectedClosingRank"] = (
    (1 - filtered_df["MeanP"]) *
    CURRENT_TOTAL_CANDIDATES
)

filtered_df.head()

C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\4033995105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["ExpectedClosingRank"] = (

,Branch,Category,Round,Domicile,MinP,MaxP,MeanP,StdP,TotalSeats,BranchSeats,TotalCandidates,Trend,ExpectedClosingRank
42,AI,UR/X/OP,R1,Y,0.882133,0.898544,0.890339,0.011605,115.5,30.500,1445106.500,-0.016411,155182.901829
91,AIAIDS,UR/X/OP,R1,Y,0.823665,0.912559,0.881559,0.035552,75.6,19.600,1169627.200,0.019270,167606.340614
136,AIML,UR/X/OP,R1,Y,0.801801,0.908346,0.874157,0.045577,74.2,20.400,1169627.200,0.026342,178081.383852
167,AIR,UR/X/OP,R1,Y,0.895425,0.895425,0.895425,0.000000,69.0,20.000,1023000.000,0.000000,147984.817009
208,AUTO,UR/X/OP,R1,Y,0.004568,0.881417,0.635342,0.364870,59.5,19.125,1070715.375,-0.100000,516030.992129

In [47]:
filtered_df["RankGap"] = (
    filtered_df["ExpectedClosingRank"] -
    user_rank
)

filtered_df.head()

C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\3729148712.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["RankGap"] = (

,Branch,Category,Round,Domicile,MinP,MaxP,MeanP,StdP,TotalSeats,BranchSeats,TotalCandidates,Trend,ExpectedClosingRank,RankGap
42,AI,UR/X/OP,R1,Y,0.882133,0.898544,0.890339,0.011605,115.5,30.500,1445106.500,-0.016411,155182.901829,64142.901829
91,AIAIDS,UR/X/OP,R1,Y,0.823665,0.912559,0.881559,0.035552,75.6,19.600,1169627.200,0.019270,167606.340614,76566.340614
136,AIML,UR/X/OP,R1,Y,0.801801,0.908346,0.874157,0.045577,74.2,20.400,1169627.200,0.026342,178081.383852,87041.383852
167,AIR,UR/X/OP,R1,Y,0.895425,0.895425,0.895425,0.000000,69.0,20.000,1023000.000,0.000000,147984.817009,56944.817009
208,AUTO,UR/X/OP,R1,Y,0.004568,0.881417,0.635342,0.364870,59.5,19.125,1070715.375,-0.100000,516030.992129,424990.992129

In [48]:
def calculate_gap_score(gap):

    if gap >= 120000:
        return 95

    elif gap >= 70000:
        return 85

    elif gap >= 30000:
        return 70

    elif gap >= 10000:
        return 55

    elif gap >= 0:
        return 40

    elif gap >= -10000:
        return 25

    else:
        return 10

In [49]:
filtered_df["GapScore"] = (
    filtered_df["RankGap"]
    .apply(calculate_gap_score)
)

filtered_df.head()

C:\Users\vansh\AppData\Local\Temp\ipykernel_33320\477625150.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["GapScore"] = (

,Branch,Category,Round,Domicile,MinP,MaxP,MeanP,StdP,TotalSeats,BranchSeats,TotalCandidates,Trend,ExpectedClosingRank,RankGap,GapScore
42,AI,UR/X/OP,R1,Y,0.882133,0.898544,0.890339,0.011605,115.5,30.500,1445106.500,-0.016411,155182.901829,64142.901829,70
91,AIAIDS,UR/X/OP,R1,Y,0.823665,0.912559,0.881559,0.035552,75.6,19.600,1169627.200,0.019270,167606.340614,76566.340614,85
136,AIML,UR/X/OP,R1,Y,0.801801,0.908346,0.874157,0.045577,74.2,20.400,1169627.200,0.026342,178081.383852,87041.383852,85
167,AIR,UR/X/OP,R1,Y,0.895425,0.895425,0.895425,0.000000,69.0,20.000,1023000.000,0.000000,147984.817009,56944.817009,70
208,AUTO,UR/X/OP,R1,Y,0.004568,0.881417,0.635342,0.364870,59.5,19.125,1070715.375,-0.100000,516030.992129,424990.992129,95

In [50]:
def calculate_probability(user_p, mean_p, std_p, trend):
    
    # Stability adjustment
    adjusted_mean = mean_p + trend
    
    # Difference
    delta = user_p - adjusted_mean
    
    # Sigmoid
    k = 25
    
    probability = 1 / (1 + np.exp(-k * delta))
    
    # Std penalty
    probability *= (1 - min(std_p, 0.3))
    
    return round(probability * 100, 2)

In [62]:
results = []

for _, row in filtered_df.iterrows():

    percentile_prob = calculate_probability(
        user_percentile,
        row["MeanP"],
        row["StdP"],
        row["Trend"]
    )

    gap_score = row["GapScore"]

    # HYBRID FUSION
    final_probability = (
        0.7 * percentile_prob +
        0.3 * gap_score
    )

    results.append({
        "Branch": row["Branch"],
        "ExpectedClosingRank": int(row["ExpectedClosingRank"]),
        "RankGap": int(row["RankGap"]),
        "PercentileProb": round(percentile_prob, 2),
        "GapScore": round(gap_score, 2),
        "FinalProbability": round(final_probability, 2)
    })

results_df = pd.DataFrame(results)

results_df.head(20)

,Branch,ExpectedClosingRank,RankGap,PercentileProb,GapScore,FinalProbability
0,AI,155182,64142,81.44,70,78.01
1,AIAIDS,167606,76566,67.99,85,73.09
2,AIML,178081,87041,67.44,85,72.71
3,AIR,147984,56944,73.22,70,72.25
4,AUTO,516030,424990,70.00,95,77.50
5,AUTO-F.W.,138423,47383,69.79,70,69.85
6,BT,205083,114043,89.00,85,87.80
7,BT-F.W.,166721,75681,79.20,85,80.94
8,CE,364618,273578,73.39,95,79.87
9,CE-F.W.,67490,-23549,39.75,10,30.82
10,CHEM,493735,402695,69.99,95,77.49
11,CHEM-F.W.,92272,1232,50.37,40,47.26
12,CSBS,186689,95649,91.55,85,89.58
13,CSD,157014,65974,72.10,70,71.47
14,CSE,80017,-11022,46.11,10,35.28
15,CSE-F.W.,44196,-46843,30.42,10,24.29
16,CST,138289,47249,69.74,70,69.82
17,EACE,305651,214611,97.79,95,96.95
18,ECE,232292,141252,84.12,95,87.38
19,ECE-F.W.,61834,-29205,37.24,10,29.07

In [63]:
def classify(prob):

    if prob >= 85:
        return "Very Safe"

    elif prob >= 70:
        return "Safe"

    elif prob >= 50:
        return "Moderate"

    elif prob >= 30:
        return "Risky"

    else:
        return "Dream"
    
results_df["CategoryType"] = (
    results_df["FinalProbability"]
    .apply(classify)
)

In [64]:
results_df = results_df.sort_values(
    by=[
        "FinalProbability"
    ],
    ascending=False
)

results_df.head(20)

,Branch,ExpectedClosingRank,RankGap,PercentileProb,GapScore,FinalProbability,CategoryType
17,EACE,305651,214611,97.79,95,96.95,Very Safe
29,MAC,298301,207261,90.26,95,91.68,Very Safe
28,ITIOT,245360,154320,89.78,95,91.35,Very Safe
22,EEIOT,533283,442243,88.05,95,90.14,Very Safe
12,CSBS,186689,95649,91.55,85,89.58,Very Safe
6,BT,205083,114043,89.00,85,87.80,Very Safe
18,ECE,232292,141252,84.12,95,87.38,Very Safe
20,EE,224142,133102,83.70,95,87.09,Very Safe
23,ET,190631,99591,84.27,85,84.49,Safe
7,BT-F.W.,166721,75681,79.20,85,80.94,Safe
27,ITAIAR,199875,108835,78.92,85,80.74,Safe
8,CE,364618,273578,73.39,95,79.87,Safe
0,AI,155182,64142,81.44,70,78.01,Safe
4,AUTO,516030,424990,70.00,95,77.50,Safe
10,CHEM,493735,402695,69.99,95,77.49,Safe
30,MECH,419775,328735,69.95,95,77.46,Safe
1,AIAIDS,167606,76566,67.99,85,73.09,Safe
2,AIML,178081,87041,67.44,85,72.71,Safe
3,AIR,147984,56944,73.22,70,72.25,Safe
13,CSD,157014,65974,72.10,70,71.47,Safe